### ISSUE TITLE
This page doesn't appear to be using Angular

### ISSUE THREAD

**Issue by stevermeister** [typebytes/ng-profiler-devtools#3]
![Screenshot 2019-09-06 at 09 50 00](https://user-images.githubusercontent.com/1526680/64410651-c5425100-d08b-11e9-881d-b8dcce51f4a9.png)

**Comment by KwintenP** [comment]
Are you using Angular 8.1+ and Ivy on this page?

Are you able to share the repo so I can see what is going wrong?

Thanks!

**Comment by stevermeister** [comment]
Hi @KwintenP! 
thank you for your fast reply.
I realized it only after some time that I needed Angular8.1 + Ivy, sorry. I've read only text in red. Maybe it's good to change error message? not to have it only in the description
